version: '3'
services:
    server:
        image: node:alpine
        container_name: simple-script-framework
        expose:
            - 8080
        working_dir: /var/www
        volumes:
            - .:/var/www
        tty: true